// <auto-generated />
using System;
using DrugPrioritizationAssistant.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrugPrioritizationAssistant.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915085940_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrugPrioritizationAssistant.Domain.Entities.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveIngredient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DosageForm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenericName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TherapeuticCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("DrugPrioritizationAssistant.Domain.Entities.DrugNeedAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DemandLevel")
                        .HasColumnType("int");

                    b.Property<int>("DomesticProductionLevel")
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<int>("ImportDependency")
                        .HasColumnType("int");

                    b.Property<decimal>("NeedScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ShortageSeverity")
                        .HasColumnType("int");

                    b.Property<int>("SupplyInstability")
                        .HasColumnType("int");

                    b.Property<int>("TherapeuticImportance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrugId")
                        .IsUnique();

                    b.ToTable("DrugNeedAssessments");
                });

            modelBuilder.Entity("DrugPrioritizationAssistant.Domain.Entities.DrugScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<decimal>("FeasibilityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("NeedScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("OpportunityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrugId")
                        .IsUnique();

                    b.ToTable("DrugScores");
                });

            modelBuilder.Entity("DrugPrioritizationAssistant.Domain.Entities.ProductionFeasibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<int>("EnzymaticRoutePotential")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentAvailability")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedYield")
                        .HasColumnType("int");

                    b.Property<decimal>("FeasibilityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PurityPotential")
                        .HasColumnType("int");

                    b.Property<int>("RawMaterialAvailability")
                        .HasColumnType("int");

                    b.Property<int>("RawMaterialCost")
                        .HasColumnType("int");

                    b.Property<int>("ScaleUpFeasibility")
                        .HasColumnType("int");

                    b.Property<int>("SynthesisComplexity")
                        .HasColumnType("int");

                    b.Property<int>("TechnicalRisk")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrugId")
                        .IsUnique();

                    b.ToTable("ProductionFeasibilities");
                });

            modelBuilder.Entity("DrugPrioritizationAssistant.Domain.Entities.DrugNeedAssessment", b =>
                {
                    b.HasOne("DrugPrioritizationAssistant.Domain.Entities.Drug", "Drug")
                        .WithOne("NeedAssessment")
                        .HasForeignKey("DrugPrioritizationAssistant.Domain.Entities.DrugNeedAssessment", "DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("DrugPrioritizationAssistant.Domain.Entities.DrugScore", b =>
                {
                    b.HasOne("DrugPrioritizationAssistant.Domain.Entities.Drug", "Drug")
                        .WithOne("Score")
                        .HasForeignKey("DrugPrioritizationAssistant.Domain.Entities.DrugScore", "DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("DrugPrioritizationAssistant.Domain.Entities.ProductionFeasibility", b =>
                {
                    b.HasOne("DrugPrioritizationAssistant.Domain.Entities.Drug", "Drug")
                        .WithOne("ProductionFeasibility")
                        .HasForeignKey("DrugPrioritizationAssistant.Domain.Entities.ProductionFeasibility", "DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("DrugPrioritizationAssistant.Domain.Entities.Drug", b =>
                {
                    b.Navigation("NeedAssessment");

                    b.Navigation("ProductionFeasibility");

                    b.Navigation("Score");
                });
#pragma warning restore 612, 618
        }
    }
}
